apiVersion: extensions/v1beta1
kind: Deployment
spec:
  replicas: 3
  template:
    spec:
      containers:
      - env: null
        name: ssd-activation-switchin-slave
        resources:
          limits:
            cpu: '122'
            memory: 6Gi
          requests:
            cpu: 1500000m
            memory: 3Gi
