apiVersion: extensions/v1beta1
kind: Deployment
spec:
  replicas: 0
  template:
    spec:
      containers:
      - env: null
        name: ssd-activation-switchin-slave
        resources:
          limits:
            cpu: '10'
            memory: 1Gi
          requests:
            cpu: 1m
            memory: 1Gi
