apiVersion: apps/v1
kind: Deployment
metadata:
  name: ciao-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ciao
  template:
    metadata:
      labels:
        app: ciao
    spec:
      containers:
      - name: ciao-container
        image: python:3.9
        command: ["python", "-c"]
        args: ["print('Hello')"]
