# Default values for bpm-domiciliazioni.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  # -- docker registry url
  repository: postesviluppo.azurecr.io/

replicaCount: 1

image:
  imageName: bpm-domiciliazioni
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  devkit: ""

# -- image pull secrets per download da docker registry con autenticazione
imagePullSecrets: [ ]

nameOverride: ""
fullnameOverride: ""

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  requests:
    cpu: "250m"
    memory: "500Mi"
  limits:
    cpu: "1000m"
    memory: "1500Mi"
